sources:
  - name: official
    displatName: "官方源"
    brewGit: "https://github.com/Homebrew/brew.git"
    coreGit: "https://github.com/Homebrew/homebrew-core.git"
    caskGit: https://github.com/Homebrew/homebrew-cask.git
    bottleDomain: https://homebrew.bintray.com

  - name: aliyun
    displatName: "阿里云"
    brewGit: "https://mirrors.aliyun.com/homebrew/brew.git"
    coreGit: "https://mirrors.aliyun.com/homebrew/homebrew-core.git"
    caskGit: "https://mirrors.aliyun.com/homebrew/homebrew-cask.git"
    bottleDomain: "https://mirrors.aliyun.com/homebrew/homebrew-bottles"

  - name: tsinghua
    displatName: "清华源"
    brewGit: "https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git"
    coreGit: "https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git"
    caskGit: "https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-cask.git"
    bottleDomain: "https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles"

  - name: ustc
    displatName: "科大源"
    brewGit: "https://mirrors.ustc.edu.cn/brew.git"
    coreGit: "https://mirrors.ustc.edu.cn/homebrew-core.git"
    caskGit: "https://mirrors.ustc.edu.cn/homebrew-cask.git"
    bottleDomain: "https://mirrors.ustc.edu.cn/homebrew-bottles"

currentSource: official
